name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: 8.2
          tools: php-cs-fixer:3.49
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  XPocketMProtocol:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: composer install
    - name: Run PHPStan
      run: vendor/bin/phpstan analyze
